### ISSUE TITLE
additional Encounter elements

### ISSUE THREAD

**Issue by James-R-Jones** [smart-on-fhir/cumulus-library#31]
4 feature requests here:

Somewhat easy codeableConcept displays that would be great to expose and count:
* Encounter.type (CC display - SNOMED term if present),
* reasonCode (CC display - SNOMED term if present), 
* hospitalization.dischargeDisposition (CC display from this guy if present: http://hl7.org/fhir/R4/valueset-encounter-discharge-disposition.html)

Would also be amazing to see if we get any Encounter.diagnosis elements populated. Ideally, a walk through any diagnosis.condition references and pull back their codes (CC display)

**Comment by dogversioning** [comment]
@James-R-Jones a :lot: of these are internal cerner codes - do you want to include those or limit to just SNOMED?

**Comment by comorbidity** [comment]
Encounter.type doesn't do much for us, no objection to adding but what is it used for? 
https://build.fhir.org/valueset-encounter-type.html

[Encounter Reason](https://build.fhir.org/valueset-encounter-reason.html) is super valuable, especially comparing to FHIR Condition for "encounter-diagnosis" vs "problem-list-item"

**hospitalization.dischargeDisposition** would be great to know if this is actually getting populated reliably by the EHR. 
In prior work efforts to pull this from Cerner it was unreliable, would be great to know if it is actually good quality now.

**Comment by comorbidity** [comment]
+1 UPVOTE this issue

**Comment by comorbidity** [comment]
BCH Can't yet do discharge disposition because the filed is not present in Cerner. 
The field is not present, possibly because BCH sample doesn't include the fields. 
Is **hospitalization** correct USCDI or should it be "admission" ? @James-R-Jones 

_Expected:_ 
https://hl7.org/fhir/encounter-definitions.html#Encounter.admission.dischargeDisposition

Actual: 

**hospitalization**
`struct<admitSource:struct<coding:array<struct<code:string,display:string,system:string,userSelected:boolean>>,text:string>,destination:struct<reference:string>,dischargeDisposition:struct<coding:array<struct<code:string,display:string,system:string,userSelected:boolean>>,text:string>,id:string>`

**Comment by comorbidity** [comment]
ReasonCode in BCH sample is not typically coded, looks like "Chief Complaint text". 

**Example: ** translation "status-post cath" is "status after insertion of catheter into the patient". No code, just text. Sometimes there is codes, but usually not. 
_[{coding=null, text=s/p cath, id=null}]_

**Comment by comorbidity** [comment]
[Act Priority](https://terminology.hl7.org/5.1.0/ValueSet-v3-ActPriority.html) also informative compared to Encounter Class, Type. 

For example, these are very important inclusion/exclusion flags for Hypertension Blood Pressure readings. 


A | **ASAP** | As soon as possible, next highest priority after stat.
CR | **callback results** | Filler should contact the placer as soon as results are available, even for preliminary results. (Was "C" in HL7 version 2.3's reporting priority.)
EL | **elective** | Beneficial to the patient but not essential for survival.
EM | **emergency** | An unforeseen combination of circumstances or the resulting state that calls for immediate action.
P | **preop** | Used to indicate that a service is to be performed prior to a scheduled surgery. When ordering a service and using the pre-op priority, a check is done to see the amount of time that must be allowed for performance of the service. When the order is placed, a message can be generated indicating the time needed for the service so that it is not ordered in conflict with a scheduled operation.
PRN | as needed | An "as needed" order should be accompanied by a description of what constitutes a need. This description is represented by an observation service predicate as a precondition.
R | **routine** | Routine service, do at usual work hours.
RR | rush reporting | A report should be prepared and sent as quickly as possible.
S | **stat** | With highest priority (e.g., emergency).
T | **timing critical** | It is critical to come as close as possible to the requested time (e.g., for a through antimicrobial level).
UD | use as directed | Drug is to be used as directed by the prescriber.
UR | urgent | Calls for prompt action.

**Comment by dogversioning** [comment]
I think most of what we can do here today is covered by previous work, #178, and the symptom extractor. If we're talking about data elements that we don't currently support, I don't think that those are library issues, per se?

So - @James-R-Jones , can we close this and break out these data asks to elsewhere?

**Comment by James-R-Jones** [comment]
Hot take for consideration as part of a wider discussion:

It would be great to _eventually_ have all the Core library tables "support" all "must support" US Core fields. Would help with our design ideology of being "self-documented" by using FHIR + USCDI. 

I'm ok closing this issue since I believe the must support items on https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-encounter.html are getting investigated by https://github.com/smart-on-fhir/cumulus-library-quality/tree/main/quality and this isn't a bug so much as a laundry list of things I'd expect folks to ask after looking at the Core profiles.

**Comment by dogversioning** [comment]
I think a good issue (both in terms of coverage and actionability) is 'Add all required fields to base core tables', and that can be done right from the spec - so that's covered by #181 now. If that works, then I'll close this one out.
